# GitHub Sponsors
# Descomente e adicione seu username do GitHub Sponsors
# github: [bernardopg]

# Patreon
# Descomente e adicione seu username do Patreon
# patreon: seu-username

# Open Collective
# Descomente e adicione seu username do Open Collective
# open_collective: seu-username

# Ko-fi
# Descomente e adicione seu username do Ko-fi
# ko_fi: seu-username

# Buy Me a Coffee
# Descomente e adicione seu username do Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/seu-username']

# Pix (para Brasil)
# Descomente e adicione sua chave Pix
# custom: ['https://nubank.com.br/pagar/sua-chave/seu-valor']

# Links Customizados
# Adicione até 4 links customizados
# custom:
#   - https://seu-site.com/donate
#   - https://seu-paypal.me/usuario
